name: Validate kernel module

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:
    inputs:
      tmate_enabled:
        description: 'Run the build with tmate debugging session enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        type: boolean
        default: false


jobs:
  validate-kernel-module:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session if enabled
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tmate_enabled == 'true' }}

      - name: Run test
        run:  |-
          ./ci/validate.sh
        shell: bash


      - name: Store artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            **/*.c
            **/*.cpp
            **/*.h
            **/*.hpp
            **/*.txt
            **/Kbuild

